### ISSUE TITLE
heatmaps

### ISSUE THREAD

**Issue by LisaHollstein** [MHH-RCUG/nf_wochenende#45]
@colindaven  I get an error for the heatmaps process:

```
 Installing packages into ‘/usr/lib/R/site-library’
  (as ‘lib’ is unspecified)
  Warning in install.packages(not_installed, repos = "http://cran.rstudio.com/") :
    'lib = "/usr/lib/R/site-library"' is not writable
  Error in install.packages(not_installed, repos = "http://cran.rstudio.com/") :
    unable to install packages
  Execution halted
  Installing packages into ‘/usr/lib/R/site-library’
  (as ‘lib’ is unspecified)
  Warning in install.packages(not_installed, repos = "http://cran.rstudio.com/") :
    'lib = "/usr/lib/R/site-library"' is not writable
  Error in install.packages(not_installed, repos = "http://cran.rstudio.com/") :
    unable to install packages
  Execution halted
```

I startet the script on a server, where R and all the peckages are installed...

**Comment by colindaven** [comment]
Thanks for the bug report. It's trying to install into a system area, which is not writable

`/usr/lib/R/site-library`

Maybe we can specify the R in the users home directory with `lib`, but I'm not sure how to do this easily.

Here, according to Bioconductor at https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html (which covers some packages, maybe all?) you can set up the bash env variable `R_LIBS_USER`

Note the R at the end of the line, which starts R (strange eh?)
`R_LIBS_USER=~/R/3.5-Bioc-3.7 R`

Then use .libPaths() to check it worked, or just run the pipeline again ?

**Comment by colindaven** [comment]
I can't test R at all, sorry. There is no R server in the cluster locally and I can't install one. 

So I can't work out and test anything for the heat maps and heat trees.

I could do it on my VM locally, but that would be a major workaround and not part of the cluster. I might have to do it though .... then run the whole wochenende locally on the VM, if that is even possible (would not be with the big refernce because of RAM ). But - at least I can test the scripts. If I copy input folders and scripts.

**Comment by LisaHollstein** [comment]
Got it! A change I had made to the bash scripts got lost, but now Rstudio is working again!
